name: Sid Ravinutala's blog
title: Sid Ravinutala's blog
url: "sidravi1.github.io"
twitter_username: sidinusofaiii
github_username: sidravi1
description: On machine learning, bayesian inference, and maybe squash
author: Sid Ravinutala
email: sid.ravi1@gmail.com
paginate: 3
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
