name: Sid Ravinutala's blog
description: On machine learning, bayesian inference, and maybe squash
author: Sid Ravinutala
email: sid.ravi1@gmail.com
paginate: 3
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
