name: Sid Ravinutala's blog
title: Sid Ravinutala
url: https://sidravi1.github.io
baseurl: ""
twitter_username: sidinusofaiii
github_username: sidravi1
description: On machine learning, bayesian inference, python, and maybe squash
author: Sid Ravinutala
email: sid.ravi1@gmail.com
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
plugins:
  - "disqus-for-jekyll"
  - jekyll-feed

header_pages:
  - resume.md
  - blog/index.html
  - index.html
